
[%bibitem]
== {blank}

title::
title.type:: main
title.content:: Guidance on Crowdsourced Bathymetry
type:: standard
docid::
docid.type:: IHO
docid.id:: B-12
docnumber:: 12
edition:: 2
language:: en
language:: fr
script:: Latn
version.revision_date:: 2020-01-20
version.draft:: 2.0.3
docstatus.stage:: in-force
date::
date.type:: published
date.from:: 2020-01-20
copyright.owner.name:: International Hydrographic Organization
copyright.owner.abbreviation:: IHO
copyright.owner.url:: www.iho.int
copyright.from:: 2020
link::
link.type:: pdf
link.content:: https://iho.int/uploads/user/pubs/bathy/B_12_Ed2.0.3_2020.pdf
place:: Monaco
validity.begins:: 2020-01-20
contributor::
contributor.organization.name:: International Hydrographic Organization
contributor.organization.abbreviation:: IHO
contributor.organization.url:: www.iho.int
contributor.role:: publisher
series::
series.type:: main
series.title.type:: original
series.title.content:: Bathymetric Publications
series.title.language:: en
series.title.script:: Latn
series.title.format:: text/plain
series.place:: Monaco
series.organization:: International Hydrographic Organization
series.number:: B
